# coding: utf-8

"""
    Eurosign

    This is the documentation of the eurosign API, you can download all of our SDK in this page.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@eurosign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.signature_requests_api import SignatureRequestsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSignatureRequestsApi(unittest.TestCase):
    """SignatureRequestsApi unit test stubs"""

    def setUp(self):
        self.api = api.signature_requests_api.SignatureRequestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_signature_requests(self):
        """Test case for cancel_signature_requests

        Cancel a signature requests  # noqa: E501
        """
        pass

    def test_create_signature_request(self):
        """Test case for create_signature_request

        Create a new signature request  # noqa: E501
        """
        pass

    def test_get_signature_request(self):
        """Test case for get_signature_request

        Get signature requests test  # noqa: E501
        """
        pass

    def test_get_signature_request_audit_trail(self):
        """Test case for get_signature_request_audit_trail

        Get the audit report of a signature requests  # noqa: E501
        """
        pass

    def test_get_signature_request_recipient(self):
        """Test case for get_signature_request_recipient

        Get a recipient of a signature requests  # noqa: E501
        """
        pass

    def test_get_signature_request_recipients(self):
        """Test case for get_signature_request_recipients

        Get recipients of a signature requests  # noqa: E501
        """
        pass

    def test_get_signature_requests(self):
        """Test case for get_signature_requests

        Get the list of signature requests  # noqa: E501
        """
        pass

    def test_send_signature_request(self):
        """Test case for send_signature_request

        Send a signature requests  # noqa: E501
        """
        pass

    def test_update_signature_request(self):
        """Test case for update_signature_request

        Update a signature requests  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
