# coding: utf-8

"""
    Eurosign

    This is the documentation of the eurosign API, you can download all of our SDK in this page.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@eurosign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse2001(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'name': 'str',
        'sender_id': 'list[Object]',
        'creation_date': 'list[Object]',
        'send_date': 'list[Object]',
        'expiration_date': 'list[Object]',
        'status': 'list[Object]',
        'recipients_order': 'list[Object]',
        'current_recipient_index': 'list[Object]'
    }

    attribute_map = {
        'uuid': 'uuid',
        'name': 'name',
        'sender_id': 'senderId',
        'creation_date': 'creationDate',
        'send_date': 'sendDate',
        'expiration_date': 'expirationDate',
        'status': 'status',
        'recipients_order': 'recipientsOrder',
        'current_recipient_index': 'currentRecipientIndex'
    }

    def __init__(self, uuid=None, name=None, sender_id=None, creation_date=None, send_date=None, expiration_date=None, status=None, recipients_order=None, current_recipient_index=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._name = None
        self._sender_id = None
        self._creation_date = None
        self._send_date = None
        self._expiration_date = None
        self._status = None
        self._recipients_order = None
        self._current_recipient_index = None
        self.discriminator = None
        if uuid is not None:
            self.uuid = uuid
        if name is not None:
            self.name = name
        if sender_id is not None:
            self.sender_id = sender_id
        if creation_date is not None:
            self.creation_date = creation_date
        if send_date is not None:
            self.send_date = send_date
        if expiration_date is not None:
            self.expiration_date = expiration_date
        if status is not None:
            self.status = status
        if recipients_order is not None:
            self.recipients_order = recipients_order
        if current_recipient_index is not None:
            self.current_recipient_index = current_recipient_index

    @property
    def uuid(self):
        """Gets the uuid of this InlineResponse2001.  # noqa: E501

        UUID of the signature request UUID  # noqa: E501

        :return: The uuid of this InlineResponse2001.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this InlineResponse2001.

        UUID of the signature request UUID  # noqa: E501

        :param uuid: The uuid of this InlineResponse2001.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def name(self):
        """Gets the name of this InlineResponse2001.  # noqa: E501

        Name of the signature request  # noqa: E501

        :return: The name of this InlineResponse2001.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2001.

        Name of the signature request  # noqa: E501

        :param name: The name of this InlineResponse2001.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def sender_id(self):
        """Gets the sender_id of this InlineResponse2001.  # noqa: E501

        ID of the sender  # noqa: E501

        :return: The sender_id of this InlineResponse2001.  # noqa: E501
        :rtype: list[Object]
        """
        return self._sender_id

    @sender_id.setter
    def sender_id(self, sender_id):
        """Sets the sender_id of this InlineResponse2001.

        ID of the sender  # noqa: E501

        :param sender_id: The sender_id of this InlineResponse2001.  # noqa: E501
        :type: list[Object]
        """

        self._sender_id = sender_id

    @property
    def creation_date(self):
        """Gets the creation_date of this InlineResponse2001.  # noqa: E501

        Creation date of the signature request  # noqa: E501

        :return: The creation_date of this InlineResponse2001.  # noqa: E501
        :rtype: list[Object]
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this InlineResponse2001.

        Creation date of the signature request  # noqa: E501

        :param creation_date: The creation_date of this InlineResponse2001.  # noqa: E501
        :type: list[Object]
        """

        self._creation_date = creation_date

    @property
    def send_date(self):
        """Gets the send_date of this InlineResponse2001.  # noqa: E501

        Sending date of the signature request  # noqa: E501

        :return: The send_date of this InlineResponse2001.  # noqa: E501
        :rtype: list[Object]
        """
        return self._send_date

    @send_date.setter
    def send_date(self, send_date):
        """Sets the send_date of this InlineResponse2001.

        Sending date of the signature request  # noqa: E501

        :param send_date: The send_date of this InlineResponse2001.  # noqa: E501
        :type: list[Object]
        """

        self._send_date = send_date

    @property
    def expiration_date(self):
        """Gets the expiration_date of this InlineResponse2001.  # noqa: E501

        Expiration date of the signature request  # noqa: E501

        :return: The expiration_date of this InlineResponse2001.  # noqa: E501
        :rtype: list[Object]
        """
        return self._expiration_date

    @expiration_date.setter
    def expiration_date(self, expiration_date):
        """Sets the expiration_date of this InlineResponse2001.

        Expiration date of the signature request  # noqa: E501

        :param expiration_date: The expiration_date of this InlineResponse2001.  # noqa: E501
        :type: list[Object]
        """

        self._expiration_date = expiration_date

    @property
    def status(self):
        """Gets the status of this InlineResponse2001.  # noqa: E501

        Status date of the signature request  # noqa: E501

        :return: The status of this InlineResponse2001.  # noqa: E501
        :rtype: list[Object]
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse2001.

        Status date of the signature request  # noqa: E501

        :param status: The status of this InlineResponse2001.  # noqa: E501
        :type: list[Object]
        """

        self._status = status

    @property
    def recipients_order(self):
        """Gets the recipients_order of this InlineResponse2001.  # noqa: E501

        Order of recipients  # noqa: E501

        :return: The recipients_order of this InlineResponse2001.  # noqa: E501
        :rtype: list[Object]
        """
        return self._recipients_order

    @recipients_order.setter
    def recipients_order(self, recipients_order):
        """Sets the recipients_order of this InlineResponse2001.

        Order of recipients  # noqa: E501

        :param recipients_order: The recipients_order of this InlineResponse2001.  # noqa: E501
        :type: list[Object]
        """

        self._recipients_order = recipients_order

    @property
    def current_recipient_index(self):
        """Gets the current_recipient_index of this InlineResponse2001.  # noqa: E501

        Index of the current recipient  # noqa: E501

        :return: The current_recipient_index of this InlineResponse2001.  # noqa: E501
        :rtype: list[Object]
        """
        return self._current_recipient_index

    @current_recipient_index.setter
    def current_recipient_index(self, current_recipient_index):
        """Sets the current_recipient_index of this InlineResponse2001.

        Index of the current recipient  # noqa: E501

        :param current_recipient_index: The current_recipient_index of this InlineResponse2001.  # noqa: E501
        :type: list[Object]
        """

        self._current_recipient_index = current_recipient_index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
