<?php
/**
 * SignatureRequestsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Eurosign
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Eurosign
 *
 * This is the documentation of the eurosign API, you can download all of our SDK in this page.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eurosign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Eurosign;

use Eurosign\Configuration;
use Eurosign\ApiException;
use Eurosign\ObjectSerializer;

/**
 * SignatureRequestsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Eurosign
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SignatureRequestsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelSignatureRequests
     *
     * Cancel a signature requests.
     *
     */
    public function testCancelSignatureRequests()
    {
    }

    /**
     * Test case for createSignatureRequest
     *
     * Create a new signature request.
     *
     */
    public function testCreateSignatureRequest()
    {
    }

    /**
     * Test case for getSignatureRequest
     *
     * Get signature requests test.
     *
     */
    public function testGetSignatureRequest()
    {
    }

    /**
     * Test case for getSignatureRequestAuditTrail
     *
     * Get the audit report of a signature requests.
     *
     */
    public function testGetSignatureRequestAuditTrail()
    {
    }

    /**
     * Test case for getSignatureRequestRecipient
     *
     * Get a recipient of a signature requests.
     *
     */
    public function testGetSignatureRequestRecipient()
    {
    }

    /**
     * Test case for getSignatureRequestRecipients
     *
     * Get recipients of a signature requests.
     *
     */
    public function testGetSignatureRequestRecipients()
    {
    }

    /**
     * Test case for getSignatureRequests
     *
     * Get the list of signature requests.
     *
     */
    public function testGetSignatureRequests()
    {
    }

    /**
     * Test case for sendSignatureRequest
     *
     * Send a signature requests.
     *
     */
    public function testSendSignatureRequest()
    {
    }

    /**
     * Test case for updateSignatureRequest
     *
     * Update a signature requests.
     *
     */
    public function testUpdateSignatureRequest()
    {
    }
}
